### ISSUE TITLE
Polymorphic not handling polymorphism in select_related()

### ISSUE THREAD

**Issue by LeGast00n** [jazzband/django-polymorphic#110]
Hi there,

I have models like this:
    from django.db import models
    from polymorphic import PolymorphicModel

```
class B(PolymorphicModel):
    pass

class B1(B):
    pass

class A(models.Model):
    b = models.ForeignKey(B)
```

Now when I run the following test, I can see that select_related() is not dealing with polymorphism of the b relation:
>>> a = A()
>>> b = B1()
>>> b.save()
>>> a.b = b
>>> a.save()
>>> saved_a = A1.objects.select_related('b').filter(pk=a.id)[0]
>>> saved_a.b.__class__
<class 'mytest.models.B'>

Any way to make it return a B1 object?

**Comment by eriktelepovsky** [comment]
Same issue here. So there is no workaround for select_related()? This should be pretty important thing as select_related() saves hundreds of queries in most of cases.

**Comment by RikSchoonbeek** [comment]
Replacing select_related with prefetch_related seems to work indeed. I had a bug due to having an instance of the parent class in memory which didn't have the method available on it that the subclass does, thus getting an error when trying to call the method.

When I replace select_related with prefetch_related this error doesn't occur.

I assume that a new query for each object that I tried to prefetch isn't executed when trying to access the related object from it's parent object, but I haven't looked at the queries being done. I might do that later.
